# Generated by Django 3.0.5 on 2020-05-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default=None, upload_to='post_img', verbose_name='Изображение'),
        ),
    ]
